CREATE TABLE Coffeeshop (
    SHOP_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    INN VARCHAR(10) NOT NULL,
    KKT VARCHAR(16) NOT NULL,
    IMAGE_URL VARCHAR(255),
    ADDRESS TEXT NOT NULL
);

CREATE TABLE Barista (
    WORKER_ID SERIAL PRIMARY KEY,
    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE Owner (
    OWNER_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE Item (
    PRODUCT_ID SERIAL PRIMARY KEY,
    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
    NAME VARCHAR(255) NOT NULL,
    PRICE INTEGER NOT NULL
);

CREATE TABLE "User" (
    USER_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(20) NOT NULL
);

CREATE TABLE Receipt (
    RECEIPT_ID SERIAL PRIMARY KEY,
    USER_ID INTEGER REFERENCES "User"(USER_ID),
    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
    TOTAL INTEGER NOT NULL,
    QR_DATA TEXT NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL
);

CREATE TABLE Reward (
    REWARD_ID SERIAL PRIMARY KEY,
    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
    NAME VARCHAR(255) NOT NULL,
    PRICE INTEGER NOT NULL,
    IMAGE_URL VARCHAR(255)
);

CREATE TABLE User_Reward (
    USER_ID INTEGER REFERENCES "User"(USER_ID),
    REWARD_ID INTEGER REFERENCES Reward(REWARD_ID),
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, REWARD_ID)
);

CREATE TABLE User_Coffeeshop (
    USER_ID INTEGER REFERENCES "User"(USER_ID),
    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
    BONUSES INTEGER DEFAULT 0,
    PRIMARY KEY (USER_ID, SHOP_ID)
);

CREATE TABLE Owner_Coffeeshop (
    OWNER_ID INTEGER REFERENCES Owner(OWNER_ID),
    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
    PRIMARY KEY (OWNER_ID, SHOP_ID)
);

CREATE TABLE Item_Receipt (
    PRODUCT_ID INTEGER REFERENCES Item(PRODUCT_ID),
    RECEIPT_ID INTEGER REFERENCES Receipt(RECEIPT_ID),
    PRIMARY KEY (PRODUCT_ID, RECEIPT_ID)
);