CREATE TABLE Coffeeshop (
    SHOP_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    INN VARCHAR(10) NOT NULL,
    KKT VARCHAR(16) NOT NULL,
    IMAGE_URL VARCHAR(255),
    ADDRESS TEXT NOT NULL
);
