CREATE TABLE Receipt (
    RECEIPT_ID SERIAL PRIMARY KEY,
    USER_ID INTEGER REFERENCES "User"(USER_ID),
    SHOP_ID INTEGER REFERENCES Coffeeshop(SHOP_ID),
    TOTAL INTEGER NOT NULL,
    QR_DATA TEXT NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL
);

