CREATE TABLE User_Reward (
    USER_ID INTEGER REFERENCES "User"(USER_ID),
    REWARD_ID INTEGER REFERENCES Reward(REWARD_ID),
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID, REWARD_ID)
);
